/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import chai from "chai";

export {};

declare global {
	// Declare global variables for tests. These are set in test/setup.js, which is included in the "files" array of tsconfig.json, so these variables are available in all test files without needing to import them.
	const nock: typeof import("nock");
	const sinon: typeof import("sinon");
	const _: typeof import("lodash");
	const assert: Chai.AssertStatic = chai.assert;
	const expect: Chai.ExpectStatic = chai.expect;
	const isBrowser: boolean;

	// The generated d.ts files from the .js files in src contain typescript types that are not properly imported.
	// These types are generated by the doc comments, but imports for them are not generated.
	// As these files are currently only consumed by other .js files, these d.ts stubs are enough to make it all work.
	type property = unknown;
	type BaseProperty = unknown;
	type NamedProperty = unknown;
	type NamedNodeProperty = unknown;
}
