/*!
 * Copyright (c) Microsoft Corporation and contributors. All rights reserved.
 * Licensed under the MIT License.
 */

import type {
	ContainerExtensionStore,
	ContainerExtension,
	ExtensionRuntime,
	InboundExtensionMessage,
} from "@fluidframework/container-definitions/internal";
import type { IContainerExperimental } from "@fluidframework/container-loader/internal";
import { assert } from "@fluidframework/core-utils/internal";
import type { IFluidContainer } from "@fluidframework/fluid-static";
import { isInternalFluidContainer } from "@fluidframework/fluid-static/internal";
import type { IContainerRuntimeBase } from "@fluidframework/runtime-definitions/internal";

import type { IPresence } from "./presence.js";
import type { PresenceExtensionInterface } from "./presenceManager.js";
import { createPresenceManager } from "./presenceManager.js";

function isContainerExtensionStore(
	manager: ContainerExtensionStore | IContainerRuntimeBase | IContainerExperimental,
): manager is ContainerExtensionStore {
	return (manager as ContainerExtensionStore).acquireExtension !== undefined;
}

/**
 * Common Presence manager for a container
 */
class ContainerPresenceManager implements ContainerExtension<never> {
	public readonly interface: IPresence;
	public readonly extension = this;
	private readonly manager: PresenceExtensionInterface;

	public constructor(runtime: ExtensionRuntime) {
		this.interface = this.manager = createPresenceManager({
			...runtime,
			submitSignal: (message) => {
				runtime.submitAddressedSignal<(typeof message)["content"]>("", message);
			},
		});
	}

	public onNewContext(): void {
		// No-op
	}

	public static readonly extensionId = "dis:bb89f4c0-80fd-4f0c-8469-4f2848ee7f4a";

	public processSignal<TType extends string, TContent>(
		address: string,
		message: InboundExtensionMessage<TType, TContent>,
		local: boolean,
	): void {
		this.manager.processSignal(address, message, local);
	}
}

/**
 * Acquire an IPresence from a Fluid Container
 * @param fluidContainer - Fluid Container to acquire the map from
 * @returns the IPresence
 *
 * @alpha
 */
export function acquirePresence(fluidContainer: IFluidContainer): IPresence {
	assert(
		isInternalFluidContainer(fluidContainer),
		0xa2f /* IFluidContainer was not recognized. Only Containers generated by the Fluid Framework are supported. */,
	);
	const innerContainer = fluidContainer.container;

	assert(
		isContainerExtensionStore(innerContainer),
		0xa39 /* Container does not support extensions. Use acquirePresenceViaDataObject. */,
	);

	const presence = innerContainer.acquireExtension(
		ContainerPresenceManager.extensionId,
		ContainerPresenceManager,
	);
	return presence;
}
